server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/user_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: AUTH-SERVER


SECURE_KEY: ${SECURE_KEY_STR:8Xc5HXT4fRYeGL5uLyNgaGg4vtMldmLhjtIvD2gLoK4=}
